# This is a workflow which will create the ephemeral environment for ActiveState Developers
name: Deploy
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branchs
  pull_request_target:
    branches: [ main ]
    types: [assigned, opened, synchronize, reopened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
   # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # This first step does a sanity check by creating a bucket
    steps:
      - name: Upload to S3
        run: aws s3 mb s3://testbucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
    # This second step runs the stack which will create the lambda function,make sure you have saved your script in a s3 bucket
    # and change the link of the file as per your need
      - name: Create the lambda function and run python script
        run: aws cloudformation create-stack --stack-name lambda2 --capabilities CAPABILITY_IAM --template-url "https://activestatebucket.s3.amazonaws.com/snapshot_lambda.yml"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
     # This third step ensure that the previous stack is completed, before the lambda function can be trigerred        
      - name: This will ensure, the previous stack is complete before we trigger the lambda functioon
        run: aws cloudformation wait stack-create-complete --stack-name lambda2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
      
      # This fourth step ensure that the lambda function is triggered and given 30 seconds to finish   
      
      - name: This will ensure, the previous stack is complete before we trigger the lambda functioon
        run: aws lambda invoke --function-name ActiveStateGetRdsSnapshotLambda2 response.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          
      - name: This will wait for the lambda to trigger and make the necessary changes before the next stack is run
        run: sleep 30
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      # This final step ensure we run the final ephemeral environment stack with latest snapshot ids
      - name: Running the final.yaml script that contains the rest of the ephimeral enviroment scripts
        run: aws cloudformation create-stack --stack-name activestateephimeral --capabilities CAPABILITY_IAM --template-url "https://activestatebucket.s3.amazonaws.com/final.yaml"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
